name: Publish on Netlify

# When workflow is triggered
on:
    push:
        branches:
            - main
            # - feature-*

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            # - name: Build
            - uses: netlify/actions/build@master
              env:
                  NETLIFY_AUTH_TOKEN: 'MaHDChLBG5UT1I5j7kuqPh4zVKl7lCyzhbMIjLC31P8' # ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NETLIFY_SITE_ID: '48a7ec73-bffc-4d2c-b8ea-59379ff0bf7d' # ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_BASE: dist/find-a-buddy
            - uses: netlify/actions/cli@master
              with:
                  args: deploy --dir=dist/find-a-buddy --functions=functions
              env:
                  NETLIFY_SITE_ID: '48a7ec73-bffc-4d2c-b8ea-59379ff0bf7d' # ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_AUTH_TOKEN: 'MaHDChLBG5UT1I5j7kuqPh4zVKl7lCyzhbMIjLC31P8' # ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_DEPLOY_MESSAGE: 'Prod deploy v${{ github.ref }}'
                  NETLIFY_DEPLOY_TO_PROD: true
                  deploy_alias: ${{ env.BRANCH_NAME }}
                  build-directory: dist/find-a-buddy
