#  Name of workflow
name: Publish on Netlify

# When workflow is triggered
on:
    push:
        branches:
            - main
            - feature-*

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: Publish
              uses: netlify/actions/build@master
              env:
                  GITHUB_TOKEN: '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' # ${{ secrets.GITHUB_TOKEN }}
                  NETLIFY_SITE_ID: '48a7ec73-bffc-4d2c-b8ea-59379ff0bf7d' # ${{ secrets.NETLIFY_SITE_ID }}
                  #   NETLIFY_BASE: ../..
                  NETLIFY_CMD: npm build
                  NETLIFY_DIR: dist/apps/find-a-buddy
                  #   NETLIFY_AUTH_TOKEN: 'MaHDChLBG5UT1I5j7kuqPh4zVKl7lCyzhbMIjLC31P8' # ${{ secrets.NETLIFY_AUTH_TOKEN }}
# - uses: actions/checkout@v1
# - uses: netlify/actions/cli@master
#   env:
#       NETLIFY_SITE_ID: '48a7ec73-bffc-4d2c-b8ea-59379ff0bf7d' # ${{ secrets.NETLIFY_SITE_ID }}
#       NETLIFY_CMD: npm build
#       NETLIFY_DIR: site/_build
#       NETLIFY_DEPLOY_MESSAGE: 'Prod deploy v${{ github.ref }}'
#       NETLIFY_DEPLOY_TO_PROD: true
#       deploy_alias: ${{ env.BRANCH_NAME }}
#       build-directory: dist/find-a-buddy
#   with:
#       args: deploy --dir=build --prod
